### ISSUE TITLE
$ curl command could not be created

### ISSUE THREAD

**Issue by GeorgeBarlow** [bojanb89pa/OAuth2Swift#1]
Any ideas on why I might be receiving a `$ curl command could not be created` when I click 'Login'? Doesn't seem to be an OAuth server issue, rather something with Alamofire.

All I've done is adjust the info.plist and use `pod install`. Just wanted to see if anyone else had come across this also.

**Comment by bojanb89pa** [comment]
@GeorgeBarlow, sorry for late answer. This is solved in this commit: f38de82db35647ee844cbfff9b55f0aa706bce37.
